nginx:
  build: ./nginx
  ports:
    - "3000:3000"
  links:
    - "app1:app1"
    - "app2:app2"
    - "app3:app3"

app1:
  build: ./app
  ports:
    - "3000"


app2:
  build: ./app
  ports:
    - "3000"

app3:
  build: ./app
  ports:
    - "3000"
